import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CoffeeIcon from '@mui/icons-material/Coffee';
import Link from 'next/link'
import Ticket from '../components/Ticket';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/> 
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to IU Tickets!
        </h1>

        <p className={styles.description}>
          Get started by posting an offer!
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/casnary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <Ticket name='Football'/>
          <Ticket name='Basketball'/>
          <Ticket name='KillRoys'/>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/SotaroKaneda"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by<CoffeeIcon/>
        </a>
      </footer>
    </div>
  )
}

