import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CoffeeIcon from '@mui/icons-material/Coffee';
import Link from 'next/link'
import Ticket from '../components/Ticket';
import Offer from '../components/Offer';


export default function Offers() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Offers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hope You Find a Good Offer!
        </h1>

        <p className={styles.description}>
          Click on offer to contact seller
        </p>

        <div className={styles.grid}>
          <Offer seller='Sotaro' price={100}/>
          <Offer seller='Sotaro' price={100}/>
          <Offer seller='Sotaro' price={100}/>
          <Offer seller='Sotaro' price={100}/>
          <Offer seller='Sotaro' price={100}/>
          <Offer seller='Sotaro' price={100}/>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/SotaroKaneda"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by<CoffeeIcon/>
        </a>
      </footer>
    </div>
  )
}

